---
id: 16905
name: test_sato_team
description: ''
user:
  id: 31
  email: admin@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: s3
    s3_connection:
      id: 16
      name: AWS - staging full access
    region: ap-northeast-1
    bucket: trocco-test-hirokoba
    path_prefix: ''
    path_match_pattern: ''
    decompression_type: guess
    skip_header_line: false
    stop_when_file_not_found: false
    custom_variables: []
    incremental_loading_enabled: false
    parser:
      type: csv
      delimiter: "\t"
      skip_header_lines: 1
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: LF
      charset: UTF-8
      columns:
      - name: uid
        type: string
      - name: url_path
        type: string
      - name: time
        type: timestamp
        format: "%Y-%m-%d %H:%M:%S %z"
      quote: "\""
      escape: "\""
    decoders: []
  out:
    type: bigquery
    bigquery_connection:
      id: 2
      name: n-analytics - production
    dataset: test_by_brett
    table: team_func_test
    auto_create_dataset: false
    mode: append
    location: US
    open_timeout_sec: 300
    timeout_sec: 300
    send_timeout_sec: 300
    read_timeout_sec: 300
    retries: 5
    allow_quoted_newlines: true
    column_options: []
    template_table: ''
    time_partitioning:
      type: 
      field: ''
      expiration_ms: 
    custom_variables: []
  data_settings:
    columns:
    - name: uid
      src: uid
      default: ''
      type: string
    - name: url_path
      src: url_path
      default: ''
      type: string
    - name: time
      src: time
      default: ''
      type: timestamp
      format: "%Y-%m-%d %H:%M:%S %z"
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
