---
id: 16906
name: test
description: ''
user:
  id: 360
  email: shinya.sato@primenumber.co.jp
transfer_option:
  transfer_type: normal
  in:
    type: sftp
    sftp_connection:
      id: 15
      name: test
    path_prefix: a
    decompression_type: guess
    custom_variables: []
    incremental_loading_enabled: false
    parser:
      type: csv
      delimiter: ","
      skip_header_lines: 0
      trim_if_not_quoted: false
      quotes_in_quoted_fields: ACCEPT_ONLY_RFC4180_ESCAPED
      allow_optional_columns: false
      allow_extra_columns: false
      max_quoted_size_limit: 131072
      stop_on_invalid_record: true
      default_timezone: UTC
      default_date: '1970-01-01'
      newline: CRLF
      columns: []
      quote: "\""
      escape: "\\"
    decoders: []
  out:
    type: sftp
    sftp_connection:
      id: 15
      name: test
    path_prefix: a
    file_ext: csv
    suppress_output_files: false
    sequence_format: "%03d.%02d."
    custom_variables: []
    formatter:
      type: csv
      delimiter: ","
      newline: CRLF
      newline_in_field: LF
      charset: UTF-8
      quote_policy: MINIMAL
      quote: "\""
      escape: "\\"
      default_timezone: UTC
    encoders: 
  is_runnable_concurrently: false
  retry_limit: 0
labels: []
job_schedules: []
triggers: []
notifications: []
