---
id: 1067
name: test_sato_datamart
description: ''
datamart:
  type: bigquery
  bigquery_connection_id: 2
  query_mode: insert
  query: |-
    SELECT
      *
    FROM
      'n-analytics.test_by_brett.fivetran_test_brett'
  destination_dataset: test_by_brett
  destination_table: team_func_test
  write_disposition: truncate
  custom_variables: []
user:
  id: 31
  email: admin@primenumber.co.jp
is_runnable_concurrently: false
labels: []
job_schedules: []
triggers: []
notifications: []
